export interface CountryCode {
  code: string;
  name: string;
  flag: string;
}

export const countryCodes: CountryCode[] = [
  { code: "+55", name: "Brasil", flag: "🇧🇷" },
  { code: "+1", name: "Estados Unidos", flag: "🇺🇸" },
  { code: "+1", name: "Canadá", flag: "🇨🇦" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+57", name: "Colômbia", flag: "🇨🇴" },
  { code: "+51", name: "Peru", flag: "🇵🇪" },
  { code: "+598", name: "Uruguai", flag: "🇺🇾" },
  { code: "+595", name: "Paraguai", flag: "🇵🇾" },
  { code: "+591", name: "Bolívia", flag: "🇧🇴" },
  { code: "+593", name: "Equador", flag: "🇪🇨" },
  { code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { code: "+592", name: "Guiana", flag: "🇬🇾" },
  { code: "+597", name: "Suriname", flag: "🇸🇷" },
  { code: "+594", name: "Guiana Francesa", flag: "🇬🇫" },
  { code: "+351", name: "Portugal", flag: "🇵🇹" },
  { code: "+34", name: "Espanha", flag: "🇪🇸" },
  { code: "+33", name: "França", flag: "🇫🇷" },
  { code: "+39", name: "Itália", flag: "🇮🇹" },
  { code: "+49", name: "Alemanha", flag: "🇩🇪" },
  { code: "+44", name: "Reino Unido", flag: "🇬🇧" },
  { code: "+31", name: "Holanda", flag: "🇳🇱" },
  { code: "+32", name: "Bélgica", flag: "🇧🇪" },
  { code: "+41", name: "Suíça", flag: "🇨🇭" },
  { code: "+43", name: "Áustria", flag: "🇦🇹" },
  { code: "+45", name: "Dinamarca", flag: "🇩🇰" },
  { code: "+46", name: "Suécia", flag: "🇸🇪" },
  { code: "+47", name: "Noruega", flag: "🇳🇴" },
  { code: "+358", name: "Finlândia", flag: "🇫🇮" },
  { code: "+353", name: "Irlanda", flag: "🇮🇪" },
  { code: "+48", name: "Polônia", flag: "🇵🇱" },
  { code: "+420", name: "República Tcheca", flag: "🇨🇿" },
  { code: "+421", name: "Eslováquia", flag: "🇸🇰" },
  { code: "+36", name: "Hungria", flag: "🇭🇺" },
  { code: "+40", name: "Romênia", flag: "🇷🇴" },
  { code: "+359", name: "Bulgária", flag: "🇧🇬" },
  { code: "+385", name: "Croácia", flag: "🇭🇷" },
  { code: "+386", name: "Eslovênia", flag: "🇸🇮" },
  { code: "+381", name: "Sérvia", flag: "🇷🇸" },
  { code: "+382", name: "Montenegro", flag: "🇲🇪" },
  { code: "+387", name: "Bósnia e Herzegovina", flag: "🇧🇦" },
  { code: "+389", name: "Macedônia do Norte", flag: "🇲🇰" },
  { code: "+355", name: "Albânia", flag: "🇦🇱" },
  { code: "+30", name: "Grécia", flag: "🇬🇷" },
  { code: "+90", name: "Turquia", flag: "🇹🇷" },
  { code: "+7", name: "Rússia", flag: "🇷🇺" },
  { code: "+380", name: "Ucrânia", flag: "🇺🇦" },
  { code: "+375", name: "Bielorrússia", flag: "🇧🇾" },
  { code: "+370", name: "Lituânia", flag: "🇱🇹" },
  { code: "+371", name: "Letônia", flag: "🇱🇻" },
  { code: "+372", name: "Estônia", flag: "🇪🇪" },
  { code: "+81", name: "Japão", flag: "🇯🇵" },
  { code: "+82", name: "Coreia do Sul", flag: "🇰🇷" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+91", name: "Índia", flag: "🇮🇳" },
  { code: "+92", name: "Paquistão", flag: "🇵🇰" },
  { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+975", name: "Butão", flag: "🇧🇹" },
  { code: "+960", name: "Maldivas", flag: "🇲🇻" },
  { code: "+93", name: "Afeganistão", flag: "🇦🇫" },
  { code: "+98", name: "Irã", flag: "🇮🇷" },
  { code: "+964", name: "Iraque", flag: "🇮🇶" },
  { code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { code: "+966", name: "Arábia Saudita", flag: "🇸🇦" },
  { code: "+971", name: "Emirados Árabes Unidos", flag: "🇦🇪" },
  { code: "+974", name: "Catar", flag: "🇶🇦" },
  { code: "+973", name: "Bahrein", flag: "🇧🇭" },
  { code: "+968", name: "Omã", flag: "🇴🇲" },
  { code: "+967", name: "Iêmen", flag: "🇾🇪" },
  { code: "+962", name: "Jordânia", flag: "🇯🇴" },
  { code: "+961", name: "Líbano", flag: "🇱🇧" },
  { code: "+963", name: "Síria", flag: "🇸🇾" },
  { code: "+972", name: "Israel", flag: "🇮🇱" },
  { code: "+970", name: "Palestina", flag: "🇵🇸" },
  { code: "+20", name: "Egito", flag: "🇪🇬" },
  { code: "+27", name: "África do Sul", flag: "🇿🇦" },
  { code: "+234", name: "Nigéria", flag: "🇳🇬" },
  { code: "+254", name: "Quênia", flag: "🇰🇪" },
  { code: "+233", name: "Gana", flag: "🇬🇭" },
  { code: "+212", name: "Marrocos", flag: "🇲🇦" },
  { code: "+216", name: "Tunísia", flag: "🇹🇳" },
  { code: "+213", name: "Argélia", flag: "🇩🇿" },
  { code: "+218", name: "Líbia", flag: "🇱🇾" },
  { code: "+251", name: "Etiópia", flag: "🇪🇹" },
  { code: "+256", name: "Uganda", flag: "🇺🇬" },
  { code: "+255", name: "Tanzânia", flag: "🇹🇿" },
  { code: "+250", name: "Ruanda", flag: "🇷🇼" },
  { code: "+257", name: "Burundi", flag: "🇧🇮" },
  { code: "+243", name: "República Democrática do Congo", flag: "🇨🇩" },
  { code: "+242", name: "República do Congo", flag: "🇨🇬" },
  { code: "+236", name: "República Centro-Africana", flag: "🇨🇫" },
  { code: "+235", name: "Chade", flag: "🇹🇩" },
  { code: "+237", name: "Camarões", flag: "🇨🇲" },
  { code: "+240", name: "Guiné Equatorial", flag: "🇬🇶" },
  { code: "+241", name: "Gabão", flag: "🇬🇦" },
  { code: "+239", name: "São Tomé e Príncipe", flag: "🇸🇹" },
  { code: "+238", name: "Cabo Verde", flag: "🇨🇻" },
  { code: "+220", name: "Gâmbia", flag: "🇬🇲" },
  { code: "+221", name: "Senegal", flag: "🇸🇳" },
  { code: "+223", name: "Mali", flag: "🇲🇱" },
  { code: "+226", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "+227", name: "Níger", flag: "🇳🇪" },
  { code: "+229", name: "Benin", flag: "🇧🇯" },
  { code: "+228", name: "Togo", flag: "🇹🇬" },
  { code: "+225", name: "Costa do Marfim", flag: "🇨🇮" },
  { code: "+224", name: "Guiné", flag: "🇬🇳" },
  { code: "+245", name: "Guiné-Bissau", flag: "🇬🇼" },
  { code: "+232", name: "Serra Leoa", flag: "🇸🇱" },
  { code: "+231", name: "Libéria", flag: "🇱🇷" },
  { code: "+61", name: "Austrália", flag: "🇦🇺" },
  { code: "+64", name: "Nova Zelândia", flag: "🇳🇿" },
  { code: "+679", name: "Fiji", flag: "🇫🇯" },
  { code: "+685", name: "Samoa", flag: "🇼🇸" },
  { code: "+676", name: "Tonga", flag: "🇹🇴" },
  { code: "+678", name: "Vanuatu", flag: "🇻🇺" },
  { code: "+687", name: "Nova Caledônia", flag: "🇳🇨" },
  { code: "+689", name: "Polinésia Francesa", flag: "🇵🇫" },
  { code: "+684", name: "Samoa Americana", flag: "🇦🇸" },
  { code: "+670", name: "Timor-Leste", flag: "🇹🇱" },
  { code: "+60", name: "Malásia", flag: "🇲🇾" },
  { code: "+65", name: "Singapura", flag: "🇸🇬" },
  { code: "+66", name: "Tailândia", flag: "🇹🇭" },
  { code: "+84", name: "Vietnã", flag: "🇻🇳" },
  { code: "+855", name: "Camboja", flag: "🇰🇭" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+95", name: "Mianmar", flag: "🇲🇲" },
  { code: "+63", name: "Filipinas", flag: "🇵🇭" },
  { code: "+62", name: "Indonésia", flag: "🇮🇩" },
  { code: "+673", name: "Brunei", flag: "🇧🇳" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+853", name: "Macau", flag: "🇲🇴" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+976", name: "Mongólia", flag: "🇲🇳" },
  { code: "+850", name: "Coreia do Norte", flag: "🇰🇵" }
];

export const getCountryByCode = (code: string): CountryCode | undefined => {
  return countryCodes.find(country => country.code === code);
};

export const getCountryByName = (name: string): CountryCode | undefined => {
  return countryCodes.find(country => 
    country.name.toLowerCase().includes(name.toLowerCase())
  );
};